version: '3.1'
services:
#  app:
#    image: apereo/cas:6.6.15

  postgre_db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
